function splitIdentifier(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replace(/[_./-]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

const zhWords: Record<string, string> = {
  none: '无',
  name: '名称',
  nickname: '昵称',
  id: 'ID',
  icon: '图标',
  composite: '复合',
  type: '类型',
  showing: '显示',
  rarity: '稀有度',
  max: '最大',
  backpack: '背包',
  stack: '堆叠',
  count: '数量',
  can: '可',
  discard: '丢弃',
  valuable: '贵重',
  tab: '分页',
  sort: '排序',
  order: '顺序',
  priority: '优先级',
  first: '首个',
  init: '初始',
  category: '分类',
  document: '文档',
  content: '内容',
  view: '查看',
  description: '描述',
  legacy: '旧版',
  debug: '调试',
  without: '无',
  obtaining: '获取',
  rare: '稀有',
  upgradeable: '可升级',
  platable: '可镀层',
  obtain: '获取',
  way: '方式',
  outcome: '产出',
  use: '使用',
  equip: '装备',
  item: '物品',
  overview: '概览',
  raw: '原始',
  display: '显示',
  basic: '基础',
  data: '数据',
  action: '动作',
  effect: '效果',
  target: '目标',
  cost: '消耗',
  text: '文本',
  confirm: '确认',
  values: '数值',
  not: '非',
  num: '数量',
  duration: '持续时间',
  cast: '施放',
  cooldown: '冷却',
  charge: '充能',
  recover: '恢复',
  upper: '上限',
  check: '检查',
  auto: '自动',
  fight: '战斗',
  params: '参数',
  param: '参数',
  blackboard: '黑板',
  buff: '增益',
  path: '路径',
  condition: '条件',
  persistent: '持续',
  depot: '仓库',
  source: '来源',
  key: '键',
  value: '值',
  str: '字符串',
  machine: '机器',
  group: '组',
  round: '轮次',
  rounds: '轮次',
  progress: '进度',
  domain: '领域',
  pack: '包',
  unlock: '解锁',
  level: '等级',
  formula: '配方',
  craft: '合成',
  factory: '工厂',
  manual: '手动',
  in: '输入',
  out: '输出',
  hub: '中枢',
  ingredients: '材料',
  outcomes: '产出',
  option: '选项',
  info: '信息',
  building: '建筑',
  full: '完整',
  attack: '攻击',
  coverage: '覆盖',
  range: '范围',
  placement: '放置',
  power: '供电',
  assets: '资源',
  scene: '场景',
  limits: '限制',
  quick: '快捷',
  bar: '栏',
  bandwidth: '带宽',
  consume: '消耗',
  needs: '需要',
  delete: '删除',
  batch: '批量',
  select: '选择',
  liquid: '液体',
  enabled: '启用',
  mark: '标记',
  panel: '面板',
  background: '背景',
  camera: '相机',
  state: '状态',
  model: '模型',
  height: '高度',
  road: '道路',
  attach: '连接',
  side: '侧',
  width: '宽度',
  depth: '深度',
  offset: '偏移',
  x: 'X',
  y: 'Y',
  z: 'Z',
  toggle: '切换',
  only: '仅',
  show: '显示',
  main: '主界面',
  input: '输入',
  output: '输出',
  ports: '端口',
  place: '放置',
  recommended: '推荐',
  rules: '规则',
  mission: '任务',
  importance: '重要度',
  character: '角色',
  reward: '奖励',
  quest: '任务',
  quests: '任务',
  previous: '前置',
  objective: '目标',
  objectives: '目标',
  dialog: '对话',
  radio: '通讯',
  messages: '消息',
  message: '消息',
  actor: '角色',
  unknown: '未知',
  enemy: '敌人',
  categories: '分类',
  distributions: '分布',
  tags: '标签',
  ability: '能力',
  abilities: '能力',
  independent: '独立',
  attributes: '属性',
  resistance: '抗性',
  scalars: '系数',
  resilience: '韧性',
  and: '与',
  super: '超级',
  armor: '护甲',
  engagement: '交战',
  profile: '画像',
  combat: '战斗',
  poise: '失衡',
  break: '击破',
  thresholds: '阈值',
  damage: '伤害',
  taken: '承受',
  grades: '等级',
  dependent: '成长',
  no: '无',
  available: '可用',
  stage: '阶段',
  threshold: '阈值',
  grade: '等级',
  scalar: '系数',
  normal: '普通',
  ore: '矿石',
  plant: '植物',
  product: '产物',
  usable: '可使用',
  doodad: '杂项',
  nurturance: '养成',
  producer: '生产',
  elite: '精英',
  boss: '首领',
  high: '高阶',
  mini: '小型',
  template: '模板',
  distribution: '分布',
  total: '总数',
  physical: '物理',
  resist: '抗性',
  nature: '自然',
  heat: '灼热',
  electric: '电磁',
  cryo: '寒冷',
  aether: '超域',
  initial: '初始',
  zero: '零',
  breaking: '打断',
  gain: '获取',
  loss: '损失',
  when: '时',
  hurt: '受击',
  interval: '间隔',
  aoi: '索敌',
  radius: '半径',
  against: '对',
  tower: '塔',
  pushed: '击退',
  back: '后退',
  coefficient: '系数',
  base: '基础',
  modifier: '修正',
  modifiers: '修正',
  attr: '属性',
  suit: '套装',
  skill: '技能',
  patch: '补丁',
  logo: '标识',
  min: '最低',
  wear: '穿戴',
  index: '索引',
  gold: '金币',
  diamond: '钻石',
  char: '干员',
  weapon: '武器',
  material: '材料',
  blueprint: '蓝图',
  ticket: '券',
  collection: '收藏',
  random: '随机',
  box: '箱',
  exp: '经验',
  card: '卡',
  logistics: '后勤',
  gift: '礼物',
  seed: '种子',
  adventure: '冒险',
  activation: '激活',
  potential: '潜能',
  case: '箱',
  spaceship: '飞船',
  coin: '代币',
  tactical: '战术',
  energy: '能量',
  settlement: '结算',
  consumable: '消耗',
  detector: '探测器',
  photo: '拍照',
  filter: '滤镜',
  music: '音乐',
  enhancement: '强化',
  user: '用户',
  avatar: '头像',
  frame: '边框',
  business: '名片',
  topic: '主题',
  exhibition: '展品',
  sticker: '贴纸',
  week: '周常',
  raid: '突袭',
  bag: '背包',
  deposit: '寄存',
  letter: '信',
  crown: '冠冕',
  feed: '投喂',
  double: '双倍',
  achievement: '成就',
  part: '部位',
};

const jaWords: Record<string, string> = {
  none: 'なし',
  name: '名称',
  nickname: '異名',
  id: 'ID',
  icon: 'アイコン',
  composite: '合成',
  type: 'タイプ',
  showing: '表示',
  rarity: 'レア度',
  max: '最大',
  backpack: 'バックパック',
  stack: 'スタック',
  count: '数',
  can: '',
  discard: '破棄',
  valuable: '貴重',
  tab: 'タブ',
  sort: '並び順',
  order: '順序',
  priority: '優先度',
  first: '最初',
  init: '初期',
  category: 'カテゴリ',
  document: '文書',
  content: '内容',
  view: '表示',
  description: '説明',
  legacy: '旧版',
  debug: 'デバッグ',
  without: 'なし',
  obtaining: '取得',
  rare: 'レア',
  upgradeable: '強化可能',
  platable: 'メッキ可能',
  obtain: '入手',
  way: '方法',
  outcome: '産出',
  use: '使用',
  equip: '装備',
  item: 'アイテム',
  overview: '概要',
  raw: 'Raw',
  display: '表示',
  basic: '基本',
  data: 'データ',
  action: 'アクション',
  effect: '効果',
  target: '対象',
  cost: 'コスト',
  text: 'テキスト',
  confirm: '確認',
  values: '数値',
  not: '非',
  num: '数',
  duration: '持続時間',
  cast: '発動',
  cooldown: 'クールダウン',
  charge: 'チャージ',
  recover: '回復',
  upper: '上限',
  check: 'チェック',
  auto: '自動',
  fight: '戦闘',
  params: 'パラメータ',
  param: 'パラメータ',
  blackboard: 'ブラックボード',
  buff: 'バフ',
  path: 'パス',
  condition: '条件',
  persistent: '持続',
  depot: '倉庫',
  source: 'ソース',
  key: 'キー',
  value: '値',
  str: '文字列',
  machine: '機械',
  group: 'グループ',
  round: 'ラウンド',
  rounds: 'ラウンド',
  progress: '進捗',
  domain: '領域',
  pack: 'パック',
  unlock: '解放',
  level: 'レベル',
  formula: 'レシピ',
  craft: '合成',
  factory: '工場',
  manual: '手動',
  in: '入力',
  out: '出力',
  hub: '中枢',
  ingredients: '材料',
  outcomes: '産出',
  option: '選択肢',
  info: '情報',
  building: '建築',
  full: '完全',
  attack: '攻撃',
  coverage: '範囲',
  range: '範囲',
  placement: '配置',
  power: '電力',
  assets: 'アセット',
  scene: 'シーン',
  limits: '制限',
  quick: 'クイック',
  bar: 'バー',
  bandwidth: '帯域',
  consume: '消費',
  needs: '必要',
  delete: '削除',
  batch: '一括',
  select: '選択',
  liquid: '液体',
  enabled: '有効',
  mark: 'マーク',
  panel: 'パネル',
  background: '背景',
  camera: 'カメラ',
  state: '状態',
  model: 'モデル',
  height: '高さ',
  road: '道路',
  attach: '接続',
  side: '側',
  width: '幅',
  depth: '奥行き',
  offset: 'オフセット',
  x: 'X',
  y: 'Y',
  z: 'Z',
  toggle: '切替',
  only: 'のみ',
  show: '表示',
  main: 'メイン',
  input: '入力',
  output: '出力',
  ports: 'ポート',
  place: '配置',
  recommended: '推奨',
  rules: 'ルール',
  mission: '任務',
  importance: '重要度',
  character: 'キャラ',
  reward: '報酬',
  quest: 'クエスト',
  quests: 'クエスト',
  previous: '前提',
  objective: '目標',
  objectives: '目標',
  dialog: '会話',
  radio: '通信',
  messages: 'メッセージ',
  message: 'メッセージ',
  actor: '話者',
  unknown: '不明',
  enemy: '敵',
  categories: 'カテゴリ',
  distributions: '分布',
  tags: 'タグ',
  ability: '能力',
  abilities: '能力',
  independent: '独立',
  attributes: '属性',
  resistance: '耐性',
  scalars: '係数',
  resilience: '靭性',
  and: 'と',
  super: 'スーパー',
  armor: 'アーマー',
  engagement: '交戦',
  profile: 'プロファイル',
  combat: '戦闘',
  poise: 'ブレイク',
  break: '破壊',
  thresholds: '閾値',
  damage: 'ダメージ',
  taken: '被',
  grades: '段階',
  dependent: '成長',
  no: 'なし',
  available: '利用可能',
  stage: '段階',
  threshold: '閾値',
  grade: '段階',
  scalar: '係数',
  normal: '通常',
  ore: '鉱石',
  plant: '植物',
  product: '産物',
  usable: '使用可能',
  doodad: '雑貨',
  nurturance: '育成',
  producer: '生産',
  elite: '精鋭',
  boss: 'ボス',
  high: '高',
  mini: 'ミニ',
  template: 'テンプレート',
  distribution: '分布',
  total: '合計',
  physical: '物理',
  resist: '耐性',
  nature: '自然',
  heat: '灼熱',
  electric: '電磁',
  cryo: '寒冷',
  aether: 'エーテル',
  initial: '初期',
  zero: 'ゼロ',
  breaking: '中断',
  gain: '獲得',
  loss: '減少',
  when: '時',
  hurt: '被弾',
  interval: '間隔',
  aoi: '索敵',
  radius: '半径',
  against: '対',
  tower: '塔',
  pushed: '押し戻し',
  back: '',
  coefficient: '係数',
  base: '基礎',
  modifier: '補正',
  modifiers: '補正',
  attr: '属性',
  suit: 'セット',
  skill: 'スキル',
  patch: 'パッチ',
  logo: 'ロゴ',
  min: '最低',
  wear: '装着',
  index: 'インデックス',
  gold: 'ゴールド',
  diamond: 'ダイヤ',
  char: 'キャラ',
  weapon: '武器',
  material: '素材',
  blueprint: '設計図',
  ticket: 'チケット',
  collection: 'コレクション',
  random: 'ランダム',
  box: 'ボックス',
  exp: 'EXP',
  card: 'カード',
  logistics: '後方支援',
  gift: 'ギフト',
  seed: '種',
  adventure: '冒険',
  activation: '活性',
  potential: '潜在',
  case: 'ケース',
  spaceship: '艦内',
  coin: 'コイン',
  tactical: '戦術',
  energy: 'エネルギー',
  settlement: '精算',
  consumable: '消耗',
  detector: '探知機',
  photo: 'フォト',
  filter: 'フィルター',
  music: '音楽',
  enhancement: '強化',
  user: 'ユーザー',
  avatar: 'アバター',
  frame: 'フレーム',
  business: '名刺',
  topic: 'テーマ',
  exhibition: '展示',
  sticker: 'ステッカー',
  week: '週次',
  raid: 'レイド',
  bag: 'バッグ',
  deposit: '寄託',
  letter: 'レター',
  crown: 'クラウン',
  feed: '投入',
  double: '倍',
  achievement: '実績',
  part: '部位',
};

const acronymMap: Record<string, string> = {
  ID: 'ID',
  HP: 'HP',
  SP: 'SP',
  EXP: 'EXP',
  ATB: 'ATB',
  AP: 'AP',
  BP: 'BP',
  UI: 'UI',
  AOI: 'AOI',
  PRTS: 'PRTS',
};

const wordOverrides: Record<string, { zh: string; ja: string; en: string }> = {
  HighLevel: { zh: '高阶', ja: '高位', en: 'High Level' },
  MiniBoss: { zh: '小型首领', ja: 'ミニボス', en: 'Mini Boss' },
  PowerPole: { zh: '电线杆', ja: '電柱', en: 'Power Pole' },
  PowerStation: { zh: '发电站', ja: '発電所', en: 'Power Station' },
  TravelPole: { zh: '传送杆', ja: '転送ポール', en: 'Travel Pole' },
  PowerTerminal: { zh: '电力终端', ja: '電力端末', en: 'Power Terminal' },
  PowerPort: { zh: '电力接口', ja: '電力ポート', en: 'Power Port' },
  PowerGate: { zh: '电力闸门', ja: '電力ゲート', en: 'Power Gate' },
  PowerDiffuser: { zh: '电力扩散器', ja: '電力ディフューザー', en: 'Power Diffuser' },
  FluidPumpIn: { zh: '液体输入泵', ja: '液体入力ポンプ', en: 'Fluid Pump In' },
  FluidPumpOut: { zh: '液体输出泵', ja: '液体出力ポンプ', en: 'Fluid Pump Out' },
  FluidReaction: { zh: '液体反应装置', ja: '液体反応装置', en: 'Fluid Reaction' },
  FluidConsume: { zh: '液体消耗装置', ja: '液体消費装置', en: 'Fluid Consume' },
  FluidSpray: { zh: '液体喷洒装置', ja: '液体噴射装置', en: 'Fluid Spray' },
  VirtualFluidContainer: {
    zh: '虚拟液体容器',
    ja: '仮想液体コンテナ',
    en: 'Virtual Fluid Container',
  },
  MachineCrafter: { zh: '机器制造台', ja: '機械製作台', en: 'Machine Crafter' },
  WeekRaid: { zh: '周常突袭', ja: '週次レイド', en: 'Week Raid' },
  DailyActivation: { zh: '每日激活', ja: '日次アクティブ', en: 'Daily Activation' },
  DomainRandGoods: { zh: '领域随机货物', ja: '領域ランダム物資', en: 'Domain Random Goods' },
  SpaceshipInfoTokens: { zh: '飞船情报代币', ja: '艦内情報トークン', en: 'Spaceship Info Tokens' },
  GemLockedTermBox: {
    zh: '源石锁定终端箱',
    ja: '源石ロック端末ボックス',
    en: 'Gem Locked Terminal Box',
  },
  BusinessCardTopic: { zh: '名片主题', ja: '名刺テーマ', en: 'Business Card Topic' },
  TicketGacha: { zh: '抽卡券', ja: 'ガチャチケット', en: 'Gacha Ticket' },
  TicketGachaLTReward: {
    zh: '长线抽卡券奖励',
    ja: '長期ガチャチケット報酬',
    en: 'Long-Term Gacha Ticket Reward',
  },
  TicketGachaLTItem: {
    zh: '长线抽卡券物品',
    ja: '長期ガチャチケットアイテム',
    en: 'Long-Term Gacha Ticket Item',
  },
  TicketWeaponBoxLTReward: {
    zh: '长线武器箱奖励券',
    ja: '長期武器箱報酬チケット',
    en: 'Long-Term Weapon Box Reward Ticket',
  },
  TicketWeaponBoxLTItem: {
    zh: '长线武器箱物品券',
    ja: '長期武器箱アイテムチケット',
    en: 'Long-Term Weapon Box Item Ticket',
  },
  GachaRecruitmentLetter: { zh: '招募信', ja: '募集レター', en: 'Recruitment Letter' },
  WeaponPotentialUp: { zh: '武器潜能提升', ja: '武器潜在強化', en: 'Weapon Potential Up' },
  CharPotentialUp: { zh: '干员潜能提升', ja: 'オペレーター潜在強化', en: 'Character Potential Up' },
  EquipEnhanceItem: { zh: '装备强化材料', ja: '装備強化素材', en: 'Equip Enhance Item' },
  FacTechPoint: { zh: '设施科技点', ja: '施設技術ポイント', en: 'Facility Tech Point' },
  spMaterial: { zh: '特种材料', ja: '特殊素材', en: 'SP Material' },
  spCrown: { zh: '特种冠冕', ja: '特殊クラウン', en: 'SP Crown' },
  APFeedIn: { zh: 'AP投入', ja: 'AP投入', en: 'AP Feed In' },
  BPDoubleReward: { zh: '通行证双倍奖励', ja: 'BP二倍報酬', en: 'BP Double Reward' },
  FuncBuilding: { zh: '功能建筑', ja: '機能建築', en: 'Functional Building' },
  ItemGrid: { zh: '物品格', ja: 'アイテムグリッド', en: 'Item Grid' },
  CardExp: { zh: '经验卡', ja: 'EXPカード', en: 'EXP Card' },
  WpnExpItem: { zh: '武器经验材料', ja: '武器EXP素材', en: 'Weapon EXP Item' },
  WpnBreakMat: { zh: '武器突破材料', ja: '武器突破素材', en: 'Weapon Break Material' },
  CharGradeUp: { zh: '干员晋升材料', ja: 'キャラ昇進素材', en: 'Character Grade Up' },
  UserAvatar: { zh: '用户头像', ja: 'ユーザーアバター', en: 'User Avatar' },
  UserAvatarFrame: { zh: '用户头像框', ja: 'ユーザーアバターフレーム', en: 'User Avatar Frame' },
};

export function localizeWarfarinIdentifier(value: string, locale = 'en-US'): string {
  const raw = value.trim();
  if (!raw) return raw;
  const override = wordOverrides[raw];
  if (override) {
    if (locale.startsWith('zh')) return override.zh;
    if (locale.startsWith('ja')) return override.ja;
    return override.en;
  }
  const words = splitIdentifier(raw);
  if (!words.length) return raw;
  if (!locale.startsWith('zh') && !locale.startsWith('ja')) {
    return words.map((word) => acronymMap[word.toUpperCase()] || word).join(' ');
  }
  const dict = locale.startsWith('zh') ? zhWords : jaWords;
  const mapped = words.map((word) => {
    const key = word.toLowerCase();
    return dict[key] ?? acronymMap[word.toUpperCase()] ?? word;
  });
  return mapped.filter((part) => part.length > 0).join(locale.startsWith('zh') ? '' : ' ');
}

export function getWarfarinEnumLabel(
  map: Record<number, string>,
  value: unknown,
  locale = 'en-US',
  fallback?: string,
): string {
  const n = typeof value === 'number' ? value : typeof value === 'string' ? Number(value) : NaN;
  if (Number.isFinite(n) && n in map) {
    return localizeWarfarinIdentifier(map[n] || '', locale);
  }
  if (fallback && fallback.trim()) return fallback;
  return Number.isFinite(n) ? `Unknown(${n})` : '-';
}

function localizeRouteWord(word: string, locale: string): string {
  const key = word.toLowerCase();
  const zhWords: Record<string, string> = {
    dungeon: '副本',
    dung: '副本',
    bossrush: '首领突袭',
    shop: '商店',
    common: '通用',
    explore: '探索',
    gacha: '寻访',
    map: '地图',
    greenticket: '绿票',
    redticket: '红票',
    lv: 'Lv',
    ss: 'SS',
  };
  const jaWords: Record<string, string> = {
    dungeon: 'ダンジョン',
    dung: 'ダンジョン',
    bossrush: 'ボスラッシュ',
    shop: 'ショップ',
    common: '共通',
    explore: '探索',
    gacha: 'ガチャ',
    map: 'マップ',
    greenticket: 'グリーンチケット',
    redticket: 'レッドチケット',
    lv: 'Lv',
    ss: 'SS',
  };
  const enWords: Record<string, string> = {
    dungeon: 'Dungeon',
    dung: 'Dungeon',
    bossrush: 'Boss Rush',
    shop: 'Shop',
    common: 'Common',
    explore: 'Explore',
    gacha: 'Gacha',
    map: 'Map',
    greenticket: 'Green Ticket',
    redticket: 'Red Ticket',
    lv: 'Lv',
    ss: 'SS',
  };
  const dict = locale.startsWith('zh') ? zhWords : locale.startsWith('ja') ? jaWords : enWords;
  return dict[key] ?? localizeWarfarinIdentifier(word, locale);
}

function formatRouteToken(token: string, locale: string): string {
  const trimmed = token.trim();
  if (!trimmed) return '';
  const direct = localizeRouteWord(trimmed, locale);
  if (direct !== trimmed) return direct;
  const match = trimmed.match(/^([a-z]+)(\d+)$/i);
  if (match) {
    const prefix = match[1] ?? '';
    const digits = match[2] ?? '';
    return `${localizeRouteWord(prefix, locale)} ${digits}`.trim();
  }
  return localizeWarfarinIdentifier(trimmed, locale);
}

function humanizeRouteId(rawId: string, prefix: string, locale: string): string {
  const normalized = rawId.trim();
  if (!normalized) return '-';
  const body = normalized.startsWith(prefix) ? normalized.slice(prefix.length) : normalized;
  const segments = body
    .split('_')
    .map((part) => formatRouteToken(part, locale))
    .filter((part) => part.length > 0);
  return segments.length ? segments.join(' · ') : normalized;
}

export function getWarfarinObtainWayLabel(id: string, locale = 'en-US'): string {
  return humanizeRouteId(id, 'item_obtain_', locale);
}

export function getWarfarinDistributionLabel(id: string, locale = 'en-US'): string {
  return humanizeRouteId(id, 'distribution_', locale);
}
